import type { IUnicodeVersionProvider } from '@xterm/xterm'
import { Unicode11Addon } from '@xterm/addon-unicode11'

// The width table we run xterm with. xterm's built-in default is Unicode 6,
// whose wcwidth gives width 1 to every codepoint above U+FFFF except CJK
// planes 2 and 3 — so an emoji was allotted one cell, drew two, and the next
// character was written over its right half (issue #27). Unicode 11 is also
// the table the programs inside the PTY are working from: glibc's wcwidth has
// been Unicode 9+ for years, so this is what keeps our column count and theirs
// in agreement.
//
// The name is ours because the table is no longer exactly the addon's. The two
// corrections below are issue #46: both are cases where the browser draws two
// cells' worth of glyph into a cell the table calls one column wide, and the
// right half of the glyph is cut off.
export const unicodeVersion = '11-emoji'

// U+FE0F VARIATION SELECTOR-16 asks for the emoji presentation of the
// character in front of it: ✔ (U+2714) is a narrow text glyph, ✔️ is the same
// character followed by the selector and every emoji font draws it square,
// across two cells.
const VARIATION_SELECTOR_16 = 0xfe0f

// Ranges Unicode 15 makes East Asian Wide that the addon's table still counts
// as one column — emoji from Unicode 12 through 15 (🫠 U+1FAE0, 🩷 U+1FA77,
// 🛜 U+1F6DC …) and the scripts added alongside them. Generated by diffing the
// addon's wcwidth against the East_Asian_Width property of Unicode 15, keeping
// only the codepoints that widen and never one that narrows, so nothing here
// can turn a combining mark into a cell of its own.
//
// Widening also agrees with the PTY rather than departing from it: glibc's
// wcwidth answers 2 for every one of these, so one column was the desync.
const WIDE_SINCE_11: readonly (readonly [number, number])[] = [
  [0x31bb, 0x31bf],
  [0x16fe4, 0x16fe4],
  [0x16ff0, 0x16ff1],
  [0x18af3, 0x18cd5],
  [0x18d00, 0x18d08],
  [0x1aff0, 0x1aff3],
  [0x1aff5, 0x1affb],
  [0x1affd, 0x1affe],
  [0x1b11f, 0x1b122],
  [0x1b132, 0x1b132],
  [0x1b155, 0x1b155],
  [0x1f6d6, 0x1f6d7],
  [0x1f6dc, 0x1f6df],
  [0x1f6fb, 0x1f6fc],
  [0x1f7f0, 0x1f7f0],
  [0x1f90c, 0x1f90c],
  [0x1f972, 0x1f972],
  [0x1f977, 0x1f979],
  [0x1f9a3, 0x1f9a4],
  [0x1f9ab, 0x1f9ad],
  [0x1f9cb, 0x1f9cc],
  [0x1fa74, 0x1fa77],
  [0x1fa7b, 0x1fa7c],
  [0x1fa83, 0x1fa88],
  [0x1fa96, 0x1fabd],
  [0x1fabf, 0x1fac5],
  [0x1face, 0x1fadb],
  [0x1fae0, 0x1fae8],
  [0x1faf0, 0x1faf8],
]

// The ranges are sorted and disjoint, and there are 29 of them; the scan stops
// at the first one that starts past the codepoint, which for ASCII — every
// other character on screen — is the first comparison.
function isWideSince11(codepoint: number): boolean {
  for (const [lo, hi] of WIDE_SINCE_11) {
    if (codepoint < lo) return false
    if (codepoint <= hi) return true
  }
  return false
}

// The packing of the number charProperties returns, which xterm's
// UnicodeService owns: bit 0 says the codepoint joins the cell in front of it,
// bits 1-2 hold the width, the rest is provider state. Only the width is
// touched here, and only through the shift, so any state rides along untouched.
const WIDTH_SHIFT = 1
const WIDTH_MASK = 0b11
const JOIN_BIT = 1

/**
 * EmojiWidths is the addon's Unicode 11 provider with the two corrections
 * above. It wraps rather than forks: the real table is some 1500 ranges, and
 * this way they stay where they are maintained.
 */
class EmojiWidths implements IUnicodeVersionProvider {
  public readonly version = unicodeVersion

  constructor(private readonly base: IUnicodeVersionProvider) {}

  public wcwidth(codepoint: number): 0 | 1 | 2 {
    const width = this.base.wcwidth(codepoint)
    return width === 1 && isWideSince11(codepoint) ? 2 : width
  }

  public charProperties(codepoint: number, preceding: number): number {
    const props = this.base.charProperties(codepoint, preceding)
    if (codepoint !== VARIATION_SELECTOR_16) return props

    // The selector is zero-width and joins the cell in front of it, so its
    // width is that cell's. Taking a one-column cell to two is exactly what
    // xterm's "combining character widens 1 column to 2" path in
    // InputHandler.print is for — it gives the cell the second column the emoji
    // glyph is going to be drawn in. A base that is already wide (👍 and the
    // rest of plane 1) is left alone: three columns would be as wrong as one.
    const joins = (props & JOIN_BIT) !== 0
    const width = (props >> WIDTH_SHIFT) & WIDTH_MASK
    return joins && width === 1 ? props + (1 << WIDTH_SHIFT) : props
  }
}

// The part of Terminal this needs. Structural, so a test can pass a stub —
// building a real Terminal takes a DOM.
export interface UnicodeCapable {
  unicode: {
    activeVersion: string
    register(provider: IUnicodeVersionProvider): void
  }
}

// applyUnicodeVersion registers the corrected provider and selects it.
// Reading or writing `unicode` at all requires the terminal to have been
// constructed with `allowProposedApi: true`; xterm throws otherwise.
//
// The addon is activated against a stub whose only job is to catch the provider
// it registers — its activate() does nothing else. That is the only way to
// reach the instance, since the package exports the addon and not the provider
// class, and the terminal itself is only ever given the wrapper.
export function applyUnicodeVersion(term: UnicodeCapable) {
  let base: IUnicodeVersionProvider | undefined
  new Unicode11Addon().activate({
    unicode: { register: (p: IUnicodeVersionProvider) => (base = p) },
  } as never)
  if (!base) throw new Error('Unicode11Addon registered no width provider')

  term.unicode.register(new EmojiWidths(base))
  term.unicode.activeVersion = unicodeVersion
}
